isEnabled = true
backgroundColor = 926762943
pressedBackgroundColor = 926762823
keyColor = -1
pressedKeyColor = -16777216
rainbowMode = false
rainbowOffset = 9
rainbowSpeed = 4
roundedBackground = true
renderInGui = true
keyShadow = true
cpsType = "ALWAYS"
displayFactor = 0.7
horizontalSlider = 20
verticalSlider = 1075
showMovement = true
showJump = true
showClick = true
